name: restaurantour
description: Flutter developer coding challenge starter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.0
  json_annotation: ^4.8.1
  flutter_svg: ^2.0.9

  # state management
  flutter_bloc: ^8.1.4

  # service locator
  get_it: ^7.6.4

  # shimer
  shimmer: ^3.0.0

  # for local DB
  shared_preferences: ^2.2.2

  # toast
  fluttertoast: ^8.2.4

  # comparing dart objects
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.2
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

  # for bloc testing
  bloc_test: ^9.1.6
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  #    - assets/svg/

  fonts:
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora/Lora-Regular.ttf
        - asset: assets/fonts/Lora/Lora-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lora/Lora-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Lora/Lora-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lora/Lora-Italic.ttf
          style: italic
        - asset: assets/fonts/Lora/Lora-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Lora/Lora-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Lora/Lora-BoldItalic.ttf
          weight: 700
          style: italic
    - family: OpenSans
      fonts:
        - asset: assets/fonts/Open_Sans/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/Open_Sans/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/Open_Sans/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/Open_Sans/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Open_Sans/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/Open_Sans/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Open_Sans/OpenSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Open_Sans/OpenSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Open_Sans/OpenSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Open_Sans/OpenSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Open_Sans/OpenSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Open_Sans/OpenSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
