name: restaurantour
description: Flutter developer coding challenge starter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.5
  flutter_svg: ^2.0.9
  freezed_annotation: ^2.4.1
  freezed: ^2.5.2
  go_router: ^13.2.0
  google_fonts: 6.1.0
  json_annotation: ^4.8.1
  pine: ^1.0.3
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.4.8
  flutter_lints: ^1.0.2
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
#  assets:
#    - assets/svg/
