name: restaurantour
description: Flutter developer coding challenge starter project.

publish_to: 'none'

version: 1.0.0+1


environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.0
  json_annotation: ^4.8.1
  flutter_svg: ^2.0.9
  envied: ^0.5.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.2
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  envied_generator: ^0.5.4+1

flutter:
  uses-material-design: true
#  assets:
#    - assets/svg/