name: restaurantour
description: Flutter developer coding challenge starter project.

publish_to: 'none'

version: 1.0.0+1


environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: 8.1.3
  dio: ^5.4.0
  json_annotation: ^4.8.1
  flutter_svg: ^2.0.9
  flutter_dotenv: ^5.1.0
  go_router: 13.0.1
  oxidized: 6.1.0
  equatable: 2.0.5
  shimmer: 3.0.0
  path_provider: ^2.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cached_network_image: ^3.3.1
  animate_do: ^3.3.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.2
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  mocktail: ^0.2.0
  bloc_test: ^9.0.1


flutter:
  uses-material-design: true
  assets:
    - .env
    - test/.env.test
    - assets/images/
    - assets/