name: restaurantour
description: Flutter developer coding challenge starter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.0
  json_annotation: ^4.9.0
  flutter_svg: ^2.0.9
  get_it: ^7.6.7
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  hive: ^2.2.3
  path_provider: ^2.1.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.2
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora-Regular.ttf
        - asset: assets/fonts/Lora-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lora-Bold.ttf
          weight: 700
